version: '3.7'

services:
  bibliobase-frontend:
    container_name: bibliobase-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
